### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by rad96** [spacem/dntviewer#2]
Translations not work with cyrillic uistrings
![2015-12-14 10_40_21-spacem github io_dntviewer_](https://cloud.githubusercontent.com/assets/2121715/11774488/312e0798-a24f-11e5-9503-3abac2e79b49.png)

**Comment by spacem** [comment]
Try now.
The xml file is too large to store it in browser storage so I reduced the size of all values to 200 characters and removed entries that were not in English. It is not really a good solution so I took that code out.
Thanks for the trying the app.

**Comment by rad96** [comment]
yeah, it's work now.
Thank you very much ^_^
